{% set version = "4.16.0" %}

package:
  name: robotframework-tidy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/robotframework-tidy/robotframework_tidy-{{ version }}.tar.gz
  sha256: 08c6ff7636e1b6a9194e695128f3edbd5edb2c332c590cb078f9b5e31d88f1ab

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  entry_points:
    - robotidy = robotidy.cli:cli

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - click >=8.1.3,<8.2
    - colorama >=0.4.3,<0.4.7
    - jinja2 >=3.1.3,<4.0
    - pathspec >=0.9.0,<0.12.2
    - python >={{ python_min }}
    - rich-click >=1.4,<1.8.6
    - robotframework >=4.0,<7.2
    - tomli ==2.0.*

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - robotidy
  commands:
    - pip check
    - robotidy --help

about:
  home: https://github.com/MarketSquare/robotframework-tidy
  summary: Code autoformatter for Robot Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
