# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 4.17.0

package:
  name: robotframework-tidy
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/r/robotframework-tidy/robotframework_tidy-${{ version }}.tar.gz
  sha256: d4247c460e79aee2efdbef9377cb41ae24142f97c3f2e4101c901232d9703e68

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - robotidy = robotidy.cli:cli

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - click 8.1.*
    - colorama >=0.4.3
    - jinja2 >=3.1.3
    - pathspec >=0.9.0
    - python >=${{ python_min }}
    - rich-click >=1.4
    - robotframework >=4.0
    - tomli >=2.0

tests:
  - python:
      imports: robotidy
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - robotidy --help

about:
  summary: Code autoformatter for Robot Framework
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/MarketSquare/robotframework-tidy
  documentation: https://robotidy.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
